add-bookings
PAZderev/java-shareit pull request #2
Opened 2024-09-07 13:14 UTC by PAZderev

Добавлена функция бронирования вещей
Добавлена функция комментариев к вещам
Переход на использование БД вместо оперативной памяти

2024-09-09 13:29 UTC, db-exp requested changes

2024-09-09 13:29 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    private String text;
+ size

2024-09-09 13:29 UTC, db-exp commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
Давай заберем из compose?
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
Это можно сделать через ${ИМЯ_ПЕРЕМЕННОЙ}

2024-09-09 13:29 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private final UserRepository userRepository;
лучше использовать "чужие" сервисы, а не репозитории - так меньше связности

2024-09-09 13:29 UTC, db-exp commented on src/main/resources/schema.sql
> +    email varchar(320),
не много?

2024-09-09 13:29 UTC, db-exp commented on src/main/resources/schema.sql
> +    text      VARCHAR(1000),
лучше не называть поля также как типы, что-то нейтральное вполне подойдет - content, например

2024-09-10 14:03 UTC, PAZderev commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    private String text;
исправил

2024-09-10 14:04 UTC, PAZderev commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
исправил, пришлось помучаться с часовыми поясами БД создавалась в часовом поясе моего компьютера, а контейнеры в UTC
Привел всё к одному часовому поясу

2024-09-10 14:05 UTC, PAZderev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private final UserRepository userRepository;
Хорошо принял, но в рамках этого тз предлагаю оставить, т.к. придется почти всё переписывать из-за того, что в сервисах не все методы прописаны

2024-09-10 14:05 UTC, PAZderev commented on src/main/resources/schema.sql
> +    email varchar(320),
Убавил

2024-09-10 14:05 UTC, PAZderev commented on src/main/resources/schema.sql
> +    text      VARCHAR(1000),
Исправил

2024-09-11 09:12 UTC, db-exp approved these changes

2024-09-14 10:45 UTC, merged